apiVersion: v1
kind: Secret
metadata:
  name: proxmox-secrets
  namespace: proxmox-controller
type: Opaque
stringData:
  # Database
  postgres-password: "CHANGE_ME_STRONG_PASSWORD"
  database-url: "postgresql+asyncpg://proxmox_user:CHANGE_ME_STRONG_PASSWORD@postgres-service:5432/proxmox_controller"
  database-url-sync: "postgresql://proxmox_user:CHANGE_ME_STRONG_PASSWORD@postgres-service:5432/proxmox_controller"
  
  # Proxmox API Token
  proxmox-token-value: "df52c07c-34b9-4b84-a695-02e64a49d97d"
  
  # GoTrue JWT Secret
  gotrue-jwt-secret: "CHANGE_ME_SUPER_SECRET_JWT_KEY_MIN_32_CHARS"
  
  # API Secret Key
  api-secret-key: "CHANGE_ME_API_SECRET_KEY_MIN_32_CHARS"
  
  # SMTP Configuration
  smtp-user: "your-email@gmail.com"
  smtp-password: "your-app-password"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxmox-config
  namespace: proxmox-controller
data:
  # Proxmox Configuration
  PROXMOX_HOST: "11.11.11.11"
  PROXMOX_PORT: "8006"
  PROXMOX_USER: "cc@pam"
  PROXMOX_TOKEN_NAME: "cc"
  PROXMOX_VERIFY_SSL: "false"
  PROXMOX_NODE: "pve"
  
  # GoTrue Configuration
  GOTRUE_API_HOST: "0.0.0.0"
  GOTRUE_API_PORT: "9999"
  API_EXTERNAL_URL: "https://your-domain.com"  # Update with your Cloudflare tunnel URL
  GOTRUE_SITE_URL: "https://your-domain.com"
  GOTRUE_URI_ALLOW_LIST: "*"
  GOTRUE_JWT_EXP: "3600"
  GOTRUE_JWT_DEFAULT_GROUP_NAME: "authenticated"
  GOTRUE_DISABLE_SIGNUP: "true"
  GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
  GOTRUE_MAILER_AUTOCONFIRM: "false"
  GOTRUE_PASSWORD_MIN_LENGTH: "8"
  GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: "false"
  
  # SMTP Configuration
  GOTRUE_SMTP_HOST: "smtp.gmail.com"
  GOTRUE_SMTP_PORT: "587"
  GOTRUE_SMTP_ADMIN_EMAIL: "admin@example.com"
  
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_RELOAD: "false"
  CORS_ORIGINS: '["https://your-domain.com"]'
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ENVIRONMENT: "production"
  
  # Database
  POSTGRES_DB: "proxmox_controller"
  POSTGRES_USER: "proxmox_user"
